---
- hosts: devserver
  become: yes
  ignore_errors: yes
  vars:
    pkg_name: httpd
    username: omar  
  tasks:
    - name: Create group
      group:
        name: manager 
        state: present

    
    - name: Creating user
      user:
        name: "{{ username }}"
        comment: Omarhilfi
        shell: /bin/bash
          # when: ansible_os_family == "Debian"
    - name: Creating
      file:
        path: /tmp/ansible.txt
        state: touch
        mode: '0600'
      register: output
    - name: read the output
      debug:
        msg: "Hello from ansable this running on {{ansible_os_family}}"  
    - name: Create directory
      file:
        path: /tmp/dir
        state: directory
        mode: '0777'
      tags:
        - app1
        - c1  
    - name: Create a file 
      shell: cat /etc/passwd | grep omar && pwd   
    - name: install apache
      yum:
        name: "{{ pkg_name }}"
        state: present
                
    - name: install finger
      package: 
        name: "{{ item }}"
        state: present   
      with_items:
        - wget
        - samba
        - java-8*
        - finger


